apiVersion: apps/v1
kind: Deployment
metadata:
  name: KC-main-micro
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-test
  template:
    metadata:
      labels:
        app: web-test
    spec:
      containers:
        - name: back-end
          image: 673380487826.dkr.ecr.eu-west-1.amazonaws.com/kc-main-micro:latest
          ports:
            - containerPort: 3000