apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kc-main-micro
  template:
    metadata:
      labels:
        app: kc-main-micro
    spec:
      serviceAccountName: kc-service-account
      containers:
        - name: back-end
          image: 673380487826.dkr.ecr.eu-west-1.amazonaws.com/kc-main-micro:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080